"""add_company_data_to_jobs

Revision ID: a15d6dc47826
Revises: 2f05e922454a
Create Date: 2026-07-07 10:55:52.388514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15d6dc47826'
down_revision: Union[str, Sequence[str], None] = '2f05e922454a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('company_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'company_data')
    # ### end Alembic commands ###
