"""add from_pipeline flag to jobs

Revision ID: f38e4f711c88
Revises: a15d6dc47826
Create Date: 2026-07-08 16:47:38.004889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38e4f711c88'
down_revision: Union[str, Sequence[str], None] = 'a15d6dc47826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('from_pipeline', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'from_pipeline')
    # ### end Alembic commands ###
